language: cpp
compiler: gcc

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update
# upgrade compilers
 - sudo apt-get install -y gcc-4.9 g++-4.9
 - sudo pip install cpp-coveralls
 - sudo rm /usr/bin/gcc && sudo ln -s /usr/bin/gcc-4.9 /usr/bin/gcc
 - sudo rm /usr/bin/g++ && sudo ln -s /usr/bin/g++-4.9 /usr/bin/g++
 - sudo rm /usr/bin/gcov && sudo ln -s /usr/bin/gcov-4.9 /usr/bin/gcov

#install:
# - if [ "${CXX}" = 'g++' ]; then export CXX="g++-4.9" && export CC="gcc-4.9"; fi;

script:
 - ./autogen.sh
 - ./configure --enable-debug
 - make check
after_success:
 - cat test-suite.log
 - gcov --version
 - coveralls --exclude test --gcov-options '\-lp'

notifications:
 - email: false
