os: linux
sudo: required

addons:
  apt:
    packages:
      - g++-5
      - gcc-5
      - nasm
    sources:
      - ubuntu-toolchain-r-test

before_install:
 - pip install --user cpp-coveralls

script:
 - g++ --version
 - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
 - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
 - g++ --version
 - ./gradlew clean make
after_success:
 - gcov --version
 - coveralls --exclude test --gcov-options '\-lp'

notifications:
 - email: false
