env: CC_X=gcc-5 CXX_X=g++-5
language: cpp
os: linux
compiler: gcc
sudo: false

addons:
  apt:
    packages:
      - g++-5
      - gcc-5
      - nasm
    sources:
      - ubuntu-toolchain-r-test

before_install:
 - pip install --user cpp-coveralls
 - g++ --version

script:
 - ./gradlew make
after_success:
 - gcov --version
 - coveralls --exclude test --gcov-options '\-lp'

notifications:
 - email: false
