os: linux
sudo: required

addons:
  apt:
    packages:
      - g++-5
      - gcc-5
      - nasm
    sources:
      - ubuntu-toolchain-r-test

before_install:
 - pip install --user cpp-coveralls

script:
 - g++ --version
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5 --slave /usr/bin/gcov gcov /usr/bin/gcov-5
 - g++ --version
 - gcov --version
 - cmake .
 - make
 - make test
after_success:
 - coveralls --exclude test --gcov-options '\-lp'

notifications:
 - email: false
