os: linux
sudo: required

addons:
  apt:
    packages:
      - g++-9
      - gcc-9
      - nasm
    sources:
      - ubuntu-toolchain-r-test

before_install:
 - pip install --user cpp-coveralls

script:
 - g++ --version
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9
 - g++ --version
 - gcov --version
 - mkdir build
 - cd build
 - cmake ..
 - make
 - make test ARGS="-V"
 - make gcov
after_success:
 - coveralls --exclude test --exclude libs --gcov-options '\-lp'

notifications:
 - email: false
