language: cpp
compiler: gcc

before_install:
# we need at least g++-4.7 for c++11 features
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update
# upgrade compilers
 - sudo apt-get install -y gcc-4.8 g++-4.8

install:
 - if [ "${CXX}" = 'g++' ]; then export CXX="g++-4.8" && export CC="gcc-4.8"; fi;

script: 
 - ./autogen.sh
 - ./configure
 - make check
