language: cpp
compiler: gcc-5
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - nasm

before_install:
  - pip install --user cpp-coveralls
  - g++ --version
   #- sudo rm /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
   #- sudo rm /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
   #- sudo rm /usr/bin/gcov && sudo ln -s /usr/bin/gcov-5 /usr/bin/gcov
   #install:
   #- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
 - ./gradlew make
after_success:
 - gcov --version
 - coveralls --exclude test --gcov-options '\-lp'

notifications:
 - email: false
